apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-app-deployment
  labels:
    app: location-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: location-app
  template:
    metadata:
      labels:
        app: location-app
    spec:
      containers:
      - name: location-app
        image: med3301/location-app:{{ .Values.image.tag }}
        ports:
        - containerPort: 8081
