apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-app-deployment
  labels:
    app: location-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-app
  template:
    metadata:
      labels:
        app: location-app
    spec:
      containers:
      - name: location-app
        image: medelharch/location-app:{{ .values.image.tag }}
        ports:
        - containerPort: 8081
